[build]
  command = "next build"
  functions = "netlify/functions"
  publish = "out"

[functions]
  # Includes all episodes from public filder
  included_files = ["public/**/*"]

[context.production]
  environment = {NEXT_PUBLIC_GA_ID: "G-XR7FPCVM7N"}


[context.deploy-preview]
  environment = {NEXT_PUBLIC_GA_ID: "test"}