[build]
  command = "next build"
  functions = "netlify/functions"
  publish = "out"

[functions]
  # Sets a custom directory for Netlify Functions
  directory = "myfunctions/"

  # Includes all Markdown files inside the "files/" directory.
  included_files = ["public/**/*"]
