name: Build check
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: bahmutov/npm-install@v1
      - run: yarn build
  test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: bahmutov/npm-install@v1
      - run: yarn test
  storybook:
    runs-on: ubuntu-latest
    name: Storybook
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: bahmutov/npm-install@v1
      - run: yarn build-storybook
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: bahmutov/npm-install@v1
      - run: yarn lint 
  prettier:
    runs-on: ubuntu-latest
    name: Prettier
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: bahmutov/npm-install@v1
      - run: yarn prettier-check 
  docker:
    runs-on: ubuntu-latest
    name: Docker
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          service_account: 'github@pbuttergirl.iam.gserviceaccount.com'
          credentials_json: ${{secrets.GCLOUD_SERVICE_ACCOUNT_KEY}}
      - run: gcloud auth configure-docker -q
      - run: docker build -t gcr.io/pbuttergirl/comic:${{github.sha}} .
      - run: docker push gcr.io/pbuttergirl/comic:${{github.sha}}

