name: Build check
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: yarn build 
  test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: yarn test 
  storybook:
    runs-on: ubuntu-latest
    name: Storybook
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: yarn build-storybook 